version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn config.wsgi:application --bind :8000
    ports:
      - "8000:8000"
    depends_on:
      - db